/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fullcycle.admin.catalogo;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
        System.out.println(new UseCase().execute());
    }
}
