/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fullcycle.admin.catalogo.application;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class UseCaseTest {
    @Test
    public void testCreateUseCase() {

    }
}
