/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fullcycle.admin.catalogo;

import com.fullcycle.admin.catalogo.infrastructure.Main;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class MainTest {
    @Test void testMain() {
        Assertions.assertNotNull(new Main());
        Main.main(new String[]{});
    }
}
